# permissions for end users to edit appscodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appscode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-kubebuilder
    app.kubernetes.io/part-of: k8s-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: appscode-editor-role
rules:
- apiGroups:
  - mycrd.k8s
  resources:
  - appscodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycrd.k8s
  resources:
  - appscodes/status
  verbs:
  - get
